acme:
  remote-address: 192.168.1.2
  security:
    users:
      - userName: admin
        password: 1234
        email: admin@demo.com
        role: ADMIN
      - userName: test
        password: test
        role: USER
    roles:
      - USER
      - ADMIN